env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby
  - rbx
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx
script: "rake test" # test:scanners"
sudo: false
