env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2
>>>>>>> de2e2acd91988e6b54f50f6c44ad85f28b68c615
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-2
script: "rake test" # test:scanners"
sudo: false
